### ISSUE TITLE
Cliente: CPF. 

### ISSUE THREAD

**Issue by albertoatcj** [PI1-GRP005-DRPTAUBATE/forno_dveneza#7]
CPF aceita menos de 11 dígitos. Há como verificar se o CPF é verdadeiro?

**Comment by Rhulin** [comment]
A data de nascimento, seria possível colocar como DD/MM/AAAA já como um pré set?

**Comment by ronaldbarbosa** [comment]
@albertoatcj  implementei a verificação de CPF com o pacote 'django-cpf'. Ele valida se o CPF tem 11 dígitos e se o cálculo dos dígitos verificadores bate com os dígitos informados. As mudanças estão na branch 'front'. Aguardo testes e feedback.
