### ISSUE TITLE
Cliente: Data de Nascimento. 

### ISSUE THREAD

**Issue by albertoatcj** [PI1-GRP005-DRPTAUBATE/forno_dveneza#8]
Campo data não preenche automaticamente no padrão com as barras entre os números DD/MM/AAAA. Há como ser automático pra facilitar a vida do cliente?

**Comment by ronaldbarbosa** [comment]
@albertoatcj  fiz a alteração para o preenchimento do campo, peço que baixe o código e faça o teste. A alteração está na branch 'front'.
