### ISSUE TITLE
Cliente: CEP, logradouro, número, complemento e referência. 

### ISSUE THREAD

**Issue by albertoatcj** [PI1-GRP005-DRPTAUBATE/forno_dveneza#9]
CEP aceita menos de 8 dígitos.
Há como autocompletar o logradouro quando CEP é preenchido?
Há como separar o número e o complemento?
Há como inserir um campo opcional de referência?

**Comment by ronaldbarbosa** [comment]
@albertoatcj a parte de separação do numero e complemento e o campo opcional pode ser adicionado no model da classe. depois que for implementado no backend eu faço a parte do frontend.

**Comment by ronaldbarbosa** [comment]
Fiz o autocomplete para os campos de endereço, bairro e cidade, a partir do CEP digitado. Mudanças estão na branch 'front'
